tag := env_var_or_default('tag', 'latest')
admin_name := env_var_or_default('admin_name', 'admin')

deploy:
    fly deploy --image-label {{tag}} --local-only --force-machines --push --region mad    

build:
    pnpm build

test:
    pnpm test