tag := env_var_or_default('tag', 'latest')
admin_name := env_var_or_default('admin_name', 'admin')

deploy:
    fly launch --image registry.fly.io/{{admin_name}}:{{tag}} --force-machines --region mad

build:
    pnpm build

test:
    pnpm test